//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beyond_Beyaan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beyond_Beyaan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occured in loading data directories: .
        /// </summary>
        internal static string A_FATAL_ERROR_OCCURED_IN_LOADING_DATA_DIRECTORIES {
            get {
                return ResourceManager.GetString("A_FATAL_ERROR_OCCURED_IN_LOADING_DATA_DIRECTORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available datasets to choose from.  Ensure that the program is installed correctly..
        /// </summary>
        internal static string BeyondBeyaan_OnLoad_There_are_no_available_datasets_to_choose_from___Ensure_that_the_program_is_installed_correctly_ {
            get {
                return ResourceManager.GetString("BeyondBeyaan_OnLoad_There_are_no_available_datasets_to_choose_from___Ensure_that_" +
                        "the_program_is_installed_correctly_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading game resources, error message: {0}
        ///.
        /// </summary>
        internal static string ERROR_LOADING_GAME_RESOURCES__ERROR_MESSAGE_0 {
            get {
                return ResourceManager.GetString("ERROR_LOADING_GAME_RESOURCES__ERROR_MESSAGE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data directories to load.
        /// </summary>
        internal static string NO_DATA_DIRECTORIES_TO_LOAD {
            get {
                return ResourceManager.GetString("NO_DATA_DIRECTORIES_TO_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VERSION_0 {
            get {
                return ResourceManager.GetString("VERSION_0", resourceCulture);
            }
        }
    }
}
